### ISSUE TITLE
My mocha is not work normal suddently, and why is about 'websocket'???

### ISSUE THREAD

**Issue by xiongzhend** [mochajs/mocha#3852]
I use to work fine with mocha in ubuntu 18.10, but somehow it output some strange error about 'websocket', so I tried reinstall mocha, or reinstall the whole nodejs, still got this: (PS: I evern try to npm install -g websock)

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/xiongzhend/Documents/dapps/LimitLess/node_modules/web3-providers-ws/src/index.js:38:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/xiongzhend/Documents/dapps/LimitLess/node_modules/web3-core-requestmanager/src/index.js:53:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/xiongzhend/Documents/dapps/LimitLess/node_modules/web3-core/src/index.js:26:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/xiongzhend/Documents/dapps/LimitLess/node_modules/web3/src/index.js:32:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/xiongzhend/Documents/dapps/LimitLess/test/LimitLess.test.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/mocha.js:324:14)
    at Mocha.run (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/mocha.js:801:10)
    at Object.exports.singleRun (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/home/xiongzhend/.npm-global/lib/node_modules/mocha/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/home/xiongzhend/.npm-global/lib/node_modules/mocha/node_modules/yargs/yargs.js:1072:28)
    at Object.parse (/home/xiongzhend/.npm-global/lib/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/xiongzhend/.npm-global/lib/node_modules/mocha/lib/cli/cli.js:62:6)
    at Object.<anonymous> (/home/xiongzhend/.npm-global/lib/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by xiongzhend** [comment]
I really don't wish to reinstall my ubuntu, any one can help:?

**Comment by plroebuck** [comment]
> I use to work fine with mocha in ubuntu 18.10, but somehow it output some strange error about 'websocket', so I tried reinstall mocha, or reinstall the whole nodejs, still got this: (PS: I evern try to npm install -g websock)

**Error has nothing to do with Mocha.** Or your version of Node.js... Or your Ubuntu installation.
Reinstalling any (or all) of them would be a waste of time.

You failed to provide requested information about related packages (e.g., "web3" version), so everything else is just guesswork...

Trivial googling points to multiple related issues raised concerning the problem.
ethereum/web3.js#1914
ethereum/web3.js#1969
ColuLocalNetwork/CLN-community-app#154

```sh
$ cd /home/xiongzhend/Documents/dapps/LimitLess
$ npm ls | grep websocket
$ npm install --save websocket          # Just install your own local copy...
$ npm test
```
