### ISSUE TITLE
📌 Mocha 12 Release Plan

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5357]
We're working on another new major version of Mocha! 📦

[Mocha 11](https://github.com/mochajs/mocha/issues/5249) was the first new major version of Mocha in 3 years. It was released on December 2nd, 2024. It contained no new bug fixes or features; it only updated the `glob` dependency (#5148 -> #5250) and raised the minimum supported Node.js version from 14.0.0 to 18.18.0 (#5206 -> #5206). The small changes were because, as mentioned in #5027, we're a new volunteer maintenance team and want to tread carefully with breaking changes.

[Mocha 12](https://github.com/mochajs/mocha/milestone/66) will also be a careful step forward. It will also contain minimal intentional breaking changes in Mocha's code. Mocha 12 will be used to:

* Bump the minimum Node.js version to `^20.19.0 || >=22.12.0`: which will allow Mocha to rely on `require(ESM)` 
* Bump all production dependencies to their latest versions - many of which are ESM-only
* Remove long-deprecated options and any other known dead code
* Remove usage of [`util.inherits`](https://nodejs.org/docs/latest/api/util.html#utilinheritsconstructor-superconstructor) and convert all manual prototype management to ECMAScript classes

You can see the full list of issues in scope under [milestone/66 v12.0.0](https://github.com/mochajs/mocha/milestone/66).

This version upgrade is intentionally meant to be "boring" for end-users. However, it's very exciting for us as maintainers -- in that it will enable us to produce new features that will be very exciting for end-users later on. That includes:

* [milestone/67 v13.0.0](https://github.com/mochajs/mocha/milestone/67): the _next_ major version, where we will start releasing long-requested user-facing breaking changes
* [projects/8 New Website](https://github.com/orgs/mochajs/projects/8): work tracking revamping our documentation website: https://mochajs.org/next

We're looking forward to continuing Mocha's modernization through 2025 and beyond. If there's anything you feel we should work on that isn't already on [Mocha's issue tracker](https://github.com/mochajs/mocha/issues), please do file it there or ask in [Mocha's Discord](https://discord.gg/KeDn2uXhER). We'd love to hear from you. 🤎 

## Remaining work

(Refresh the page for the latest)

- [x] Switch release-please to betas
- [x] Close https://github.com/mochajs/mocha/milestone/66
- [x] Switch release-please to release candidates (#6083)
- [x] Release `12.0.0-rc.1` (#6061, might require fixing #6073, but that issue may be v11-specific)
- [x] Post prerelease docs (#5848)
- [x] Announce RC 1 on [Discord](https://discord.com/invite/KeDn2uXhER)
- [x] Wait a month for bug reports, fix bugs, and wait until we're ready
- [ ] Switch release-please to releases (#6084)
- [ ] Write up release docs
- [ ] Release 12.0.0!
- [ ] Announce Mocha 12 Stable on Discord and wherever!

**Comment by JoshuaKGoldberg** [comment]
Mocha 11.7.* has a lot of changes related to native Node.js require(esm) support.
* 11.7.0 included #5366, which unlocked a lot of use cases
* 11.7.1 included #5384, which fixed a few resultant issues

I'd like to wait a bit longer for Mocha 12 to let the new Node.js support stabilize. Many scenarios stopped working in newer versions of Node.js without any changes in Mocha. Some were broken by the new support changing the ordering or behavior of imports and/or requires. It's a very tricky area. At the very least, I'd personally like to see resolutions to:

* #5392
* #5393
* #5396

**Comment by valadaptive** [comment]
Maybe it'd be a good idea to create a `v11` branch (for any future v11 fixes) and move forward with modernization in the meantime? Or vice versa, create a `v12` branch and start working on things in there. The more v12 PRs start piling up, the harder they'll be to merge, and it may be better to have them all in one branch instead of sitting unmerged.

**Comment by JoshuaKGoldberg** [comment]
We're almost ready to start merging v12's changes! With all the issues linked in https://github.com/mochajs/mocha/issues/5357#issuecomment-3035961293 resolved, the ESM/imports side of things is ready to go.

I think there's just one fix we'd like to add in v11, #5355 & #5374 -> #5379. I'll focus on that for a bit and then come back to 12.

**Comment by JoshuaKGoldberg** [comment]
We're cleared to merge the v12 breaking changes into `main` now. 🚀 

If anything needs to be backported into `v11`, we can always branch off from 8649f394e469b0ec8612837b84707ac42ad2af62 (11.7.4).

**Comment by mark-wiemer** [comment]
Better late than never: do we have plans for a migration guide or handwritten change announcement? Or do we think release-please notes will be sufficient since the only user-facing change will be Node versions and browser versions? Maybe I'm just thinking out loud and I'll have clearer thoughts when the actual changelog is ready to review :)

**Comment by JoshuaKGoldberg** [comment]
Good call, I think we should file issues:

1. For switching release-please to prerelease (i.e. #5478)
2. For writing up prerelease docs
3. For writing up stable release docs
4. For switching release-please back to stable

**Comment by mark-wiemer** [comment]
I'd rather just have those be checkboxes on this one, is that OK? I've edited the issue description to reflect the same

**Comment by mark-wiemer** [comment]
We're getting ever-closer! @mochajs/maintenance-crew what are your thoughts around "prerelease docs" and "release docs"? We already have auto-generated docs list items, of course, do we need anything more for this? I'm thinking a quick manual note clarifying the scope of changes and maybe a reference to https://github.com/mochajs/mocha/blob/557473828570f8883c55cb0e450f153f3f9f8f74/MAINTAINERS.md#major-releases

Otherwise the auto-generated stuff is good enough for me, provided it covers everything from 11.x to 12.0 (not just the last RC to the first full release)

**Comment by JoshuaKGoldberg** [comment]
I think that's a good idea. We should also put "make a blog post explaining the new version" into our processes, if it's not there yet.

**Comment by JoshuaKGoldberg** [comment]
Alas, #5837 did not complete the v12 release.

**Comment by voxpelli** [comment]
Oops, copy and paste mistake, I entered the correct issue number but forgot to remove the trigger keyword.

**Comment by mark-wiemer** [comment]
> [Mocha 12](https://github.com/mochajs/mocha/milestone/66) will also be a careful step forward. It will also contain no new features or intentional breaking changes in Mocha's code. Instead, Mocha 12 will be used to:

@JoshuaKGoldberg OK if we change this to:

> [Mocha 12](https://github.com/mochajs/mocha/milestone/66) will also be a careful step forward. It will also contain minimal intentional breaking changes in Mocha's code. Mocha 12 will be used to:

There are probably some new features and there is at least one intentional breaking change (#5025)

**Comment by JoshuaKGoldberg** [comment]
Yeah good call. I agree, and also think it better conveys the original intent.

**Comment by YasharF** [comment]
Not sure if you are already planning for this, but now that Node 20 is in EoL, and considering this is a major version release, you can potentially simplify the engine requirement by just setting it to `>=22.12.0`.  
On a similar note, it might also be worth adding Node.js 26 as "experimental" in the docs and adding it to the GitHub Action workflows (as a non‑blocking step, etc.). Node 26 is going to be tagged as LTS some months from now, so I personally wouldn't officially try to block a release for supporting it, but for my own projects I have regular builds for future‑proofing and planning. Let me know if you would like me to help with a PR.

**Comment by voxpelli** [comment]
> Not sure if you are already planning for this, but now that Node 20 is in EoL, and considering this is a major version release, you can potentially simplify the engine requirement by just setting it to `>=22.12.0`.  

For a package like Mocha I would wait with this until next major release. We're bumping quite far as we are and have yet to reap all the gains from it.

But good call! And yes, we should test against Node 26, I would accept a PR for that 👍

**Comment by Yahsfa** [comment]
Do you folks have an idea of when V12 is going to be officially released? V11 has dependencies with cve considered high so I may need to pick it up as soon as there is an official release. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Nothing specific, I'm afraid. We've all been pretty low bandwidth on Mocha the last few weeks+. But there is steady progress on the last main area of blockers (#5400's CJS -> ESM migration). 

I know this might not be doable for you / everyone, the Mocha 12.x beta versions are generally stable and ready to be tried. They're tagged as `next` on npm: e.g. [`mocha@12.0.0-beta-9.2`](https://www.npmjs.com/package/mocha/v/12.0.0-beta-9.2). They're all "feature complete" minus whatever's left in [milestone/66 v12.0.0](https://github.com/mochajs/mocha/milestone/66). We'd really appreciate you / anybody trying them out and letting us know if there are any subtle breakages we missed! 🤎

**Comment by mark-wiemer** [comment]
I'll elaborate that I'm extremely low bandwidth this month due to a [long illness](https://markwiemer.com/blog/penultimate-health-update/) that started in March. I plan to return in early June and I'm eager (as is Josh) to release v12. We're very close to feature complete, and we have some ideas for how to accelerate the time-consuming CJS to ESM transition that is the main blocker. I don't want to give any firm deadlines, but I'd personally be sad if we didn't get v12 released as stable in June.

**Comment by thescientist13** [comment]
Just wanted to share that there was some feedback around the docs supporting the introduction of ESM configuration files - https://github.com/mochajs/mocha/pull/5397#discussion_r3316100857

I went ahead and opened a docs PR for consideration - https://github.com/mochajs/mocha/pull/6027

Figured this would be something to consider as part of the v12 milestone.  Let me know your thoughts.

**Comment by mark-wiemer** [comment]
Updated the plan to reflect new pre-release notes in our new blog, clarifying that we'll wait about a month + however long it takes to be stable, and announcements in Discord :)

**Comment by mark-wiemer** [comment]
We are very proud to announce the first Mocha 12 release candidate! We've also created a blog for future Mocha announcements!

Mocha 12 is the first release to follow our even-odd major release pattern. As an even release, Mocha 12 introduces very few breaking changes: We’ve bumped our Node floor, removed some long-deprecated features, and modernized a bit, but everything else works just as before.

Learn more at https://mochajs.org/blog/mocha-12-rc-1/ 🤎 (updated link)

**Comment by mark-wiemer** [comment]
And now we wait for a month... fun! Expect plenty of bugfixes between now and v12 stable :)

**Comment by SchroederSteffen** [comment]
> Learn more at https://mochajs.org/blog/mocha-12/ 🤎

Correct link is https://mochajs.org/blog/mocha-12-rc-1/ since https://github.com/mochajs/mocha/pull/6106.

**Comment by mark-wiemer** [comment]
We released RC 5 today and we hope it'll be the last RC! We are aware of some potential breaking changes introduced with adding the `exports` field instead of the `main` field and will be evaluating those before releasing Mocha 12.0.0. At this point, I believe there are only three things to do before releasing v12:

- [x] Investigate potential breaking changes introduced by #6168 (will be tracked here for simplicity)
- [x] Stress-test Mocha 12 RC 5 with extensive ad-hoc tests focusing on changed areas, encoding tests into our automated suite when reasonable
- [x] Ensure users have had ~1-2 weeks with RC 5 and no blocking new issues have been reported

Thanks for your patience everyone, we're almost there!

**Comment by EhabY** [comment]
Is it possible to run something like `npm audit fix`? since there seems to be a few critical and high severity issues that could be fixed by a minor/patch bump.

**Comment by mark-wiemer** [comment]
@EhabY those have always been false negatives for us, ref #5781

**Comment by mostafaNazari702** [comment]
I installed rc.4 and rc.5 side by side to isolate it since they only differ by the package.json field.

`exports` breaks CJS's `require()` of a deep path with no file extension so `require('mocha/lib/stats-collector')` and `require('mocha/lib/reporters/base')` stop resolving. Anything with an extension is fine, as are mocha, mocha/package.json, and mocha/mocha.js / mocha/mocha.css`.

ESM is untouched since it always needed extensions and webpack's resolver gives identical results on both versions, browser field included. So it's Node-only, CJS-only, extensionless-only.

and mochawesome already fails on rc.4 with `Cannot find module 'mocha/lib/utils'` from the .js to .cjs renames so reverting exports wouldn't fix it. And every third-party reporter i tried (mochawesome, mocha-junit-reporter, mocha-multi-reporters, mocha-jenkins-reporter) dies on `TypeError: Class constructor Base cannot be invoked without 'new'`, because they all do `Base.call(this, runner)`. Two of them are having it in a try/catch and just lose stats silently which is arguably worse than crashing.

**Comment by mostafaNazari702** [comment]
I got rc.5 to use `"main": "./index.js"` instead of exports. The DEP0151 warning goes away, and extensionless deep requires keep working, and webpack resolution is same. The warning is literally "No main or exports field" so main is enough and skips the encapsulation exports brings. Might suit a boring v12 better with a real exports map in v13. Nothing in our own lib/ , bin/ or test/ self-references mocha so dropping it is safe for us. (i also tried `"./*": ["./*", "./*.js"]` to keep both forms working, node doesn't fall back on missing files it just breaks everything.

**Comment by intity** [comment]
@mark-wiemer 
>Ensure users have had ~1-2 weeks with RC 5 and no blocking new issues have been reported

Am I correct in understanding that the release date is being pushed back by another 1-2 weeks?

**Comment by mark-wiemer** [comment]
https://mochajs.org/blog/mocha-12-stable/ 🤎
