### ISSUE TITLE
Cannot find module issue with mocha.js in browser

### ISSUE THREAD

**Issue by killmenot** [mochajs/mocha#3091]
Hi,

I'm using mocha with requirejs for browser testing and got a weird issue when updated to 4.0.1. 

By some reason I got the following issue when run tests:
<img width="594" alt="screenshot 2017-11-03 20 26 37" src="https://user-images.githubusercontent.com/119337/32387371-538f8e64-c0d5-11e7-8887-0c0250895722.png">

You can find the code that reproduce the issue here: https://github.com/killmenot/mocha-cannot-find-module-issue (just do `npm install` and then open testrunner.html in browser or run `npm run test`)

I took a look at mocha.js (I run `make mocha.js`) I found the following:
<img width="888" alt="screenshot 2017-11-03 20 28 40" src="https://user-images.githubusercontent.com/119337/32387469-998ec29a-c0d5-11e7-80e1-da1d3e427392.png">

When I remove `require=` from mocha.js file the test works fine.

Any advices?

**Comment by ScottFreeCode** [comment]
Someone will have to figure out whether our Browserify options changed or if the Browserify defaults changed in the newer version and either way how to change it back with the version we now use.

(At some point, we need to get tests using Karma with an AMD loader such as RequireJS so that these get caught before releasing...)

**Comment by boneskull** [comment]
Yes, I added `--require buffer:buffer` which evidently broke stuff.

**Comment by boneskull** [comment]
@killmenot please pull down PR #3145 to test a fix

**Comment by killmenot** [comment]
@boneskull PR #3145 fixes this issue. Thank you

**Comment by Bamieh** [comment]
closing this as it is fixed by dropping ie9 and ie10 support (fixed by https://github.com/mochajs/mocha/pull/3164)
