### PR TITLE
fix bundling; closes #3091

### LINKED ISSUE #3091: Cannot find module issue with mocha.js in browser
Hi,

I'm using mocha with requirejs for browser testing and got a weird issue when updated to 4.0.1. 

By some reason I got the following issue when run tests:
screenshot 2017-11-03 20 26 37

You can find the code that reproduce the issue here: https://github.com/killmenot/mocha-cannot-find-module-issue (just do `npm install` and then open testrunner.html in browser or run `npm run test`)

I took a look at mocha.js (I run `make mocha.js`) I found the following:
screenshot 2017-11-03 20 28 40

When I remove `require=` from mocha.js file the test works fine.

Any advices?

### PR DESCRIPTION
**Pull request by boneskull**
This became too difficult to manage on the command-line.

What we're trying to do here is ship a version of the `Buffer` shim
which plays well with IE9/IE10.  Browserify ships with a version which
does NOT play well, meaning we have to force it to use the version
we choose (`buffer@4.9.x`).

The fix is in two parts:

1.  `insertGlobalVars` option replaces usages of global `Buffer` with
`require('/path/to/mocha/node_modules/buffer').Buffer`
2.  Any *other* module which explicitly requires `buffer` or, yes,
`buffer/`, must *also* use `/path/to/mocha/node_modules/buffer`

If *both* of these are not in place, Browserify will use its *own*
version of the `buffer` shim.

### CODE REVIEW

**Comment by boneskull** [comment]
WIP pending some way of testing this so it doesn't happen again.

**Comment by boneskull** [comment]
oh also this is necessary because `—require` in browserify doesn’t just “alias” stuff like the “browser” field of `package.json` which doesn’t work for any modules outside of your own sources anyway...

**Comment by boneskull** [comment]
I started to wonder if this would be easier with Webpack then realized the build script I just wrote is likely smaller than even the most basic Webpack config 😬

**Comment by Bamieh** [comment]
@boneskull I highly discourage using webpack in mocha, mainly because it overrides the native module implementation of node, which might lead to really odd bugs for some end users. It also limits some possible features of mocha, such as using node VMs for isolating the runner from the user code.

**Comment by boneskull** [comment]
@Bamieh We don't bundle for Node.js, only for the browser.  So we don't need to worry about native modules getting blasted

**Comment by Bamieh** [comment]
@boneskull okay, i will test this at my work tomorrow because we have the appropriate testing environment for this issue.

**Comment by boneskull** [comment]
@Bamieh I've automated it.. please review

File: Makefile [hunk 1]
```diff
@@ -1,14 +1,14 @@
-BROWSERIFY := "node_modules/.bin/browserify"
+BROWSERIFY := "scripts/build.js"
 KARMA := "node_modules/.bin/karma"
 MOCHA := "bin/mocha"
 NYC := "node_modules/.bin/nyc"
 
 ifdef COVERAGE
 define test_node
-	$(NYC) --no-clean --report-dir coverage/reports/$(1) $(MOCHA)
+$(NYC) --no-clean --report-dir coverage/reports/$(1) $(MOCHA)
```
Comment (boneskull) [inline Makefile]: from what I can tell the leading tab here is unneccessary

File: Makefile [hunk 2]
```diff
@@ -1,14 +1,14 @@
...
 endef
 else
-	test_node := $(MOCHA)
+test_node := $(MOCHA)
```
Comment (boneskull) [inline Makefile]: and here

File: karma.conf.js [hunk 3]
```diff
@@ -4,6 +4,9 @@ var fs = require('fs');
 var path = require('path');
 var mkdirp = require('mkdirp');
 var baseBundleDirpath = path.join(__dirname, '.karma');
+var builder = require('./scripts/build');
```
Comment (boneskull) [inline karma.conf.js]: this allows us to reuse the config in karma

File: karma.conf.js [hunk 4]
```diff
@@ -32,23 +35,24 @@ module.exports = function (config) {
...
-        b.ignore('glob')
-          .ignore('fs')
-          .ignore('path')
-          .ignore('supports-color')
-          .require(path.join(__dirname, 'node_modules', 'buffer'), {expose: 'buffer'})
+        build(b)
           .on('bundled', function (err, content) {
-            if (!err && bundleDirpath) {
+            if (err) {
+              throw err;
```
Comment (boneskull) [inline karma.conf.js]: apparently we were eating errors before... oops.

File: karma.conf.js [hunk 5]
```diff
@@ -32,23 +35,24 @@ module.exports = function (config) {
...
+            }
+            if (bundleDirpath) {
               // write bundle to directory for debugging
-              fs.writeFileSync(path.join(bundleDirpath,
-                'bundle.' + Date.now() + '.js'), content);
+              fs.writeFileSync(path.join(bundleDirpath, 'mocha.' + Date.now() +
```
Comment (boneskull) [inline karma.conf.js]: I changed this filename

File: karma.conf.js [hunk 6]
```diff
@@ -124,21 +117,50 @@ module.exports = function (config) {
...
+        'test/interfaces/' + MOCHA_TEST + '.spec.js'
+      ];
+      break;
+
+    case 'esm':
+      // for now we will only run against Chrome to test this.
+      if (cfg.sauceLabs) {
+        cfg.sauceLabs.testName = 'ESM Integration Tests';
+        cfg.browsers = ['chrome@latest'];
+        var launcher = cfg.customLaunchers['chrome@latest'];
```
Comment (boneskull) [inline karma.conf.js]: sorry this is awkward; we need to update the dev scripts to ES2015+.

File: karma.conf.js [hunk 7]
```diff
@@ -124,21 +117,50 @@ module.exports = function (config) {
...
+        cfg.customLaunchers = {
+          'chrome@latest': launcher
+        };
+      } else if (!env.TRAVIS) {
+        cfg.browsers = ['Chrome'];
```
Comment (boneskull) [inline karma.conf.js]: what other browsers currently support native modules? @mochajs/core

File: karma.conf.js [hunk 8]
```diff
@@ -124,21 +117,50 @@ module.exports = function (config) {
...
+      } else {
+        console.error(
+          'skipping ESM tests & exiting; no SauceLabs nor local run detected');
+        process.exit(0);
+      }
+      cfg.files = [
+        'test/browser-fixtures/esm.fixture.html',
```
Comment (boneskull) [inline karma.conf.js]: can we force Karma to load a `.js` file as a module instead of script?  I have no idea.

File: test/browser-fixtures/esm.fixture.html [hunk 9]
```diff
@@ -0,0 +1,7 @@
+<script>
+  delete window.require;
```
Comment (boneskull) [inline test/browser-fixtures/esm.fixture.html]: this ensures that breakage will occur if the suffix on the distfile is bad.

Comment (boneskull) [reply test/browser-fixtures/esm.fixture.html]: see #3139 for what I mean

**Comment by boneskull** [comment]
You know, it might be a better idea to just land #3148 instead.

File: karma.conf.js (hunk 7 above)
Comment (Bamieh) [reply karma.conf.js]: in accordance to MDN

> This feature is only just beginning to be implemented in browsers natively at this time. It is implemented in many transpilers, such as TypeScript and Babel, and bundlers such as Rollup and Webpack.

image

**Comment by Bamieh** [comment]
@boneskull i am totally in favor of #3148 instead of these hacks. But we should keep the tests you wrote if we agree on dropping support for IE9, IE10.

**Comment by boneskull** [comment]
need to pull my tests out of here
