### PR TITLE
feat: use require to load esm

### LINKED ISSUE #5314: 🐛 Bug: Node.js v23 testing with .ts files
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

Minimal reproduction repo: https://github.com/legendecas/mocha-register-node-v23
- Test with @babel/register, with typescript preset
- Test with ts-node

Run `npm test` should pass in either Node.js v23, or Node.js v22.

### Actual

Node.js v22 passes the test.

Node.js v23 fails with error:

```
(node:51969) Warning: Failed to load the ES module: /Developer/notebook/mocha-register/test/mytest.test.ts. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

 Exception during run: /Developer/notebook/mocha-register/test/mytest.test.ts:1
import { foo } from './mymod';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at loadCJSModule (node:internal/modules/esm/translators:122:25)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:207:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
    at async formattedImport (/Developer/notebook/mocha-register/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async Object.exports.requireOrImport (/Developer/notebook/mocha-register/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async Object.exports.loadFilesAsync (/Developer/notebook/mocha-register/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/Developer/notebook/mocha-register/node_modules/mocha/lib/cli/run-helpers.js:162:3)
    at async Object.exports.handler (/Developer/notebook/mocha-register/node_modules/mocha/lib/cli/run.js:375:5)
```

### Minimal, Reproducible Example

Minimal reproduction repo: https://github.com/legendecas/mocha-register-node-v23

Existing ts projects can be written in module syntax for static analysis and transpiled to CJS. These workflows assume that these TS files are loaded as CJS modules. However, in this case, mocha will try to `import` a `.ts` file first, and try `require` if `import` fails, and a default enabled ts loader takes precedence over user configuered CJS loader.

https://github.com/mochajs/mocha/blob/b0c269616e775689f4f28eedc0a9c5e99048139b/lib/nodejs/esm-utils.js#L37-L53

Alternatives:
- Use `--no-experimental-strip-types` in user code.
- Use `package.json#type` to determine `import`/`require` which should be used to load a test file first in mocha. 
- Node.js ESM loader should also respect `require.extensions`? 

Just throwing ideas. /cc @marco-ippolito

### Versions

- `mocha --version`: `11.1.0`
- `node_modules/.bin/mocha --version`: `11.1.0`
- `node --version`: `v23.10.0`

### Additional Info

- https://github.com/nodejs/node/pull/57298#issuecomment-2739658745
- https://github.com/open-telemetry/opentelemetry-js/issues/5415

### LINKED ISSUE #5317: 🐛 Bug: Syntax error with @babel/register, JSX and latest Node.js 20 LTS (require ESM) only when run via Mocha
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

A test to pass, using:
1. Mocha 11.2.0
2. [@babel/register](https://babeljs.io/docs/babel-register) (with [env](https://babeljs.io/docs/babel-preset-env) and [react](https://babeljs.io/docs/babel-preset-react) presets)
3. Node.js 20 LTS ([v20.19.0](https://nodejs.org/en/blog/release/v20.19.0))
    1. This is the first release with [require ESM](https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/) enabled by default.

#### Test code
```javascript
import assert from 'node:assert'
import { isValidElement } from 'react'
import Component from "./component";

describe('component test', () => {
    it('exports a component', () => {
        assert.equal(isValidElement(<Component />), true);
    });
});
```

#### Source code under test
```javascript
export default function Component () {
    return (
        <p>Test component</p>
    );
}
```

#### Output using Node.js v20.18.3
```shell
mocha "src/**.test.js"

  component test
    ✔ exports a component


  1 passing (1ms)
```

#### Output using Node.js v20.19.0

The test fails with a syntax error

```shell
 mocha "src/**.test.js"

 Exception during run: SyntaxError[ @/src/component.test.js ]: Unexpected token '<'
    at compileSourceTextModule (node:internal/modules/esm/utils:340:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:146:18)
    at #translate (node:internal/modules/esm/loader:431:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:478:27)
    at async ModuleJob._link (node:internal/modules/esm/module_job:110:19)
```

### Minimal, Reproducible Example

* [mbtts/babel-node-mocha-test](https://github.com/mbtts/babel-node-mocha-test)

The repository README highlights the relevant scripts (`start` and `test`, along with expected output).

### Versions

```shell
> mocha --version
11.2.0
```

```shell
> node_modules/.bin/mocha --version
11.2.0
```

✅  Working Node.js version:
```shell
node --version
v20.18.3
```

❌  Broken Node.js version:
```shell
> node --version
v20.19.0
```

### Additional Info

* Babel register is still able to run the same code with Node.js (but without Mocha)
   * This is the primary reason I am filing as a Mocha issue **first**, but I appreciate Node.js have changed the behaviour with the minor update and the require ESM feature.
* The problem is triggered by the use of JSX syntax in JS files. Because the file has a `.js` file extension, Node.js ESM loader is attempting to perform import analysis/processing on it **before** the request intercepted by [pirates](https://www.npmjs.com/package/pirates) (Babel register). This source analysis crashes because it cannot parse the syntax.
    * If the files are renamed from `.js` to use a `.jsx` extension then the analysis is **not** performed, the request is handed on to babel register and the tests pass. This is the simplest/easiest workaround, especially in small projects.
* The reason Babel register is still able to run the same code with Node.js (but _without_ Mocha) appears to be because it never passes through the (Node.js) ESM loader and so the import analysis/processing is **not** performed. I believe this line from [esm-utils.js](https://github.com/mochajs/mocha/blob/fbceb19bbdad121f0100ec3434258775bd87aeaf/lib/nodejs/esm-utils.js#L35) in Mocha is forcing code to be loaded through the ESM loader, even in a CJS environment.
    * In other words, Babel register with exactly the same configuration works when used directly with Node.js in an exclusively CJS environment:
        ```shell
        node --require @babel/register src/index.js
        
        <p>Test component</p>
        ```

I mostly wanted to let you know and document it as I suspect I won’t be the only person to hit this problem.

Many thanks!

### PR DESCRIPTION
**Pull request by legendecas**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5314, fixes #5317
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This allows compilers based on `require.extensions` continue to work, like `ts-node` with Node.js built-in TypeScript support enabled.

Hopefully unblock https://github.com/nodejs/node/pull/57298.

Fixes: https://github.com/mochajs/mocha/issues/5314
Fixes: https://github.com/mochajs/mocha/issues/5317

### CODE REVIEW

**Review by marco-ippolito — APPROVED** [review]

**Comment by marco-ippolito** [comment]
friendly ping @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for the ping! I was out for a bit and am catching up on things now. I'm going to try to get to testing this thoroughly this week (hopefully tomorrow or so). But the more folks who can test this out, the better.

Note that we're pretty close to releasing Mocha 12 (#5357). I also have a vague memory of someone mentioning somewhere that once Mocha drops support for pre-`require(esm)` versions of Node.js, this whole area of code could be simplified. I don't have the time to spelunk for it right now, but will if nobody posts that soon.

IMO it might make sense to either...
* ⚡ Faster: Merge this in as a feature in Mocha 11.x, then take on the drastic simplification in Mocha 12
* 🦺 More careful: merge this in as a feature in Mocha 12.0, then file the simplification as a followup (either Mocha 12 or Mocha 13, depending on how breaking it is)

I'm personally leaning to ⚡ since this change is pretty targeted, and because of how broken things are at the moment for Node.js versions with type stripping. cc @mochajs/committers - WDYT?

**Comment by JoshuaKGoldberg** [comment]
Oh and @legendecas in the meantime, could you please try to fix the lint error? It's failing in CI.

**Comment by legendecas** [comment]
Fixed lint issue.

"Merge this in as a feature in Mocha 11.x, then take on the drastic simplification in Mocha 12" sounds good to me!

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 Fantastic! Thanks for sending this in, it's really clean and I haven't been able to break it locally when testing on a bunch of real-world repos.

We should definitely get another review from @mochajs/committers if possible just to be safe. But no blockers from me on merging to main in v11.

**Review by mark-wiemer — APPROVED** [review]

File: eslint.config.js [hunk 1]
```diff
@@ -61,7 +61,8 @@ module.exports = [
       'lib/nodejs/esm-utils.js',
       'rollup.config.js',
       'scripts/*.mjs',
-      'scripts/pick-from-package-json.js'
+      'scripts/pick-from-package-json.js',
+      'test/compiler-cjs/test.js'
```
[the remark this answers is not in the document]
Comment (legendecas) [reply eslint.config.js:65]: we don't have typescript-eslint configured so we can not add this ts file.

**Comment by JoshuaKGoldberg** [comment]
Just to be safe, I ran this PR's changes through another set of tests today on:

- https://github.com/eslint/eslint
- https://github.com/Microsoft/TypeScript
- https://github.com/legendecas/mocha-register-node-v23 (from #5314)
- https://github.com/mbtts/babel-node-mocha-test (from #5317)

...across Node.js versions:

- 18.18.0
- 20.9.0
- 21.1.0
- 22.16.0
- 23.11.1
- 24.2.0

Confirmed that this fixes both of those issues and generally works. Great! I'll merge this now and publish a new release.

**Comment by JoshuaKGoldberg** [comment]
Just to be safe, I ran this PR's changes through another set of tests today on:

- https://github.com/eslint/eslint
- https://github.com/Microsoft/TypeScript
- https://github.com/legendecas/mocha-register-node-v23 (from #5314)
- https://github.com/mbtts/babel-node-mocha-test (from #5317)

...across Node.js versions:

- 18.18.0
- 20.9.0
- 21.1.0
- 22.16.0
- 23.11.1
- 24.2.0

Confirmed that this fixes both of those issues and generally works. Great! I'll merge this now and publish a new release. Thanks a bunch @legendecas for the clean fix and patience with us on the PR review, this is great work! Additional shoutout to @marco-ippolito from the Node.js side and for helping push it forward. 🔥

**Comment by JoshuaKGoldberg** [comment]
Released as `11.7.0`:

* https://github.com/mochajs/mocha/releases/tag/v11.7.0
* https://www.npmjs.com/package/mocha/v/11.7.0

🎉

**Comment by AviVahl** [comment]
This PR has the unfortunate side-effect of removing support for setups that use [asynchronous Node.js loaders/hooks](https://nodejs.org/docs/latest/api/module.html#customization-hooks).

Before this PR: 
try `import()`. if that fails- try `require()`.

After this PR: 
try `require()`. if that fails **and error is ERR_REQUIRE_ASYNC_MODULE**- try `import()`.
if `require()` fails for any other reason (e.g. needing the hooks being registered), it won't even try to `import()`, not making use of any asynchronous hooks.

**Comment by queengooborg** [comment]
Looks like this change had broken testing on MDN's browser-compat-data: https://github.com/mdn/browser-compat-data/actions/runs/15731639024/job/44333918076?pr=27094

>  Exception during run: Error: Transform failed with 1 error:
/home/runner/work/browser-compat-data/browser-compat-data/index.ts:56:15: ERROR: Top-level await is currently not supported with the "cjs" output format

Also affecting the mdn-bcd-collector project in the same way: https://github.com/openwebdocs/mdn-bcd-collector/actions/runs/15732266958/job/44335981656?pr=2479

Not sure if it's an issue with `tsx` in particular, but something seems to be blocking us from upgrading to Mocha v11.7.  Will try to dig in to see if it's something with our setup tomorrow!

**Comment by JoshuaKGoldberg** [comment]
Lovely. Thanks @AviVahl and @queengooborg, that's good to know. Any investigation you can do would be greatly appreciated. Fixing this area is a high priority for Mocha right now.

**Comment by mshima** [comment]
@JoshuaKGoldberg it breaks mocha with custom ts loader. https://github.com/jhipster/generator-jhipster/pull/29827
It's probably because the required module doesn't exist so it does not fallback to import due to condition.
Typescript loaders takes a non existing `.js`  module and tries to load `.ts` alternative and I think there is no loader support for require.
I will do some test.

**Comment by MuTsunTsai** [comment]
It also breaks `@hyperse/ts-node/register`. It was working in Mocha 11.6.0.

**Comment by JoshuaKGoldberg** [comment]
We believe we have a fix:

1. #5383: adds a test that exercises at least one of the kinds of cases now failing in 11.7.0
2. #5384 fixes at least all of the cases that have been reported:
    * #5380
    * #5387
    * #5388

If anybody is seeing a new error as of Mocha 11.7.0 that's _not_ in any of those issues (and doesn't reproduce on Mocha 11.6.0) please do file a new issue.
