### ISSUE TITLE
`--inspect` flag doesn't work

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3681]
When I tried to debug mocha with `--inspect` option, `ReferenceError: describe is not defined` error occurred. 
 It seems it is not run under `mocha` context.

```sh
$ ./node_modules/.bin/mocha --version
6.0.0-1

$ ./node_modules/.bin/mocha --inspect ex.test.js
Debugger listening on ws://127.0.0.1:9229/aca2ad85-76ab-42ac-99bc-6acb84bd1bc2
For help, see: https://nodejs.org/en/docs/inspector
/Users/outsider/temp/mocha-next/6/ex.test.js:1
(function (exports, require, module, __filename, __dirname) { describe('Suite', () => {
                                                              ^

ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/outsider/temp/mocha-next/6/ex.test.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

With `mocha@5.2.0`, it is fine.

```sh
$ ./node_modules/.bin/mocha --version
5.2.0

$ ./node_modules/.bin/mocha --inspect ex.test.js
Debugger listening on ws://127.0.0.1:9229/4b56feea-1711-43bd-82a3-5a587171122f
For help, see: https://nodejs.org/en/docs/inspector


  Suite
    ✓ test


  1 passing (5ms)
```

**Comment by outsideris** [comment]
I tried to fix this issue, but I could find a good solution. Any idea? /cc @mochajs/core 

```sh
$ ./bin/mocha --inspect example.js

  mocha:cli exec /Users/outsider/bin/lib/node.js/node-v10.15.0-darwin-x64/bin/node w/ args: [ '--inspect',
  'example.js',
  '/Users/outsider/mocha/bin/_mocha',
  '--timeout',
  '200',
  '--no-config',
  '--no-package',
  '--no-opts',
  '--require',
  'test/setup',
  '--ui',
  'bdd',
  '--global',
  'okGlobalA',
  '--global',
  'okGlobalB',
  '--global',
  'okGlobalC',
  '--global',
  'callback*',
  '--diff',
  '--extension',
  'js',
  '--reporter',
  'spec',
  '--slow',
  '75' ] +2ms
Debugger listening on ws://127.0.0.1:9229/296e0480-0771-4977-b4cd-539b3795ad71
For help, see: https://nodejs.org/en/docs/inspector

ReferenceError: describe is not defined
```

In [here](https://github.com/mochajs/mocha/blob/master/bin/mocha#L24), [yargs-parser](https://github.com/yargs/yargs-parser) parsed `example.js` as `--inspect`'s value. Other [Node flags](https://nodejs.org/api/cli.html#cli_options) are same.

So, below works.

```sh
$ ./bin/mocha --inspect --exit example.js

  mocha:cli exec /Users/outsider/bin/lib/node.js/node-v10.15.0-darwin-x64/bin/node w/ args: [ '--inspect',
  '/Users/outsider/mocha/bin/_mocha',
  'example.js',
  '--timeout',
  '200',
  '--exit',
  '--no-config',
  '--no-package',
  '--no-opts',
  '--require',
  'test/setup',
  '--ui',
  'bdd',
  '--global',
  'okGlobalA',
  '--global',
  'okGlobalB',
  '--global',
  'okGlobalC',
  '--global',
  'callback*',
  '--diff',
  '--extension',
  'js',
  '--reporter',
  'spec',
  '--slow',
  '75' ] +2ms
Debugger listening on ws://127.0.0.1:9229/a2e27603-7321-4eb3-97dd-f0e64f224f2a
For help, see: https://nodejs.org/en/docs/inspector

  1 passing (3ms)
```

And this also works.

```sh
$ ./bin/mocha example.js --inspector

  mocha:cli exec /Users/outsider/bin/lib/node.js/node-v10.15.0-darwin-x64/bin/node w/ args: [ '--inspect',
  '/Users/outsider/mocha/bin/_mocha',
  'example.js',
  '--timeout',
  '200',
  '--no-config',
  '--no-package',
  '--no-opts',
  '--require',
  'test/setup',
  '--ui',
  'bdd',
  '--global',
  'okGlobalA',
  '--global',
  'okGlobalB',
  '--global',
  'okGlobalC',
  '--global',
  'callback*',
  '--diff',
  '--extension',
  'js',
  '--reporter',
  'spec',
  '--slow',
  '75' ] +2ms
Debugger listening on ws://127.0.0.1:9229/a09fc498-5626-4023-94bd-e7eb1c8352e7
For help, see: https://nodejs.org/en/docs/inspector

  1 passing (2ms)
```

However this doesn't work, because [yargs-unparser](https://github.com/yargs/yargs-unparser) unparsed `--inspect: 27.0.0.1:1234` as `--inspect 127.0.0.1:1234` not `--inspect=127.0.0.1:1234` in [here]([](https://github.com/mochajs/mocha/blob/master/bin/mocha#L90)).

```sh
$ ./bin/mocha example.js --inspect=127.0.0.1:1234

  mocha:cli exec /Users/outsider/bin/lib/node.js/node-v10.15.0-darwin-x64/bin/node w/ args: [ '--inspect',
  '127.0.0.1:1234',
  '/Users/outsider/mocha/bin/_mocha',
  'example.js',
  '--timeout',
  '200',
  '--no-config',
  '--no-package',
  '--no-opts',
  '--require',
  'test/setup',
  '--ui',
  'bdd',
  '--global',
  'okGlobalA',
  '--global',
  'okGlobalB',
  '--global',
  'okGlobalC',
  '--global',
  'callback*',
  '--diff',
  '--extension',
  'js',
  '--reporter',
  'spec',
  '--slow',
  '75' ] +2ms
Debugger listening on ws://127.0.0.1:9229/a77b7761-4aad-42fb-ba61-a96ab2c4490b
For help, see: https://nodejs.org/en/docs/inspecto

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/outsider/mocha/127.0.0.1:1234'
```

**Comment by boneskull** [comment]
@outsideris see here https://github.com/mochajs/mocha/blob/0f95a7d73355ce9ab299c9f8dfa983b897ecf2fc/lib/cli/options.js#L290

we may want to do the opposite--take everything from `_` and put it into `--spec`.  (`--spec` is an alias for the default positional arguments; the "files" in other words)

does that help?

**Comment by juergba** [comment]
Have a look at https://github.com/mochajs/mocha/issues/3683#issuecomment-457184246
Maybe your issue has the same cause as mine.

**Comment by boneskull** [comment]
looks like we may just need to special-case this.

**Comment by boneskull** [comment]
basically that involves doing something like what v5.2.0 does for some node flags that optionally accept an argument.

FWIW, `--inspect 0.0.0.0:12345 foo.spec.js` does *not* work on Mocha v5.2.0 either, and I wouldn't expect it to; the `=` is required.

**Comment by juergba** [comment]
We could require users to distinguish between mocha flags and node flags. All node flags have to be attached at the end of CL, separated by the end parsing sign "--". 
Mocha would just pass these node flags to Node, without any checks or whatever. Node would do the parsing for us.
Like "npm" running a script: `npm run server -- --port=1337`

**Comment by boneskull** [comment]
@juergba 	That'd be easier to implement, but also it'd break backwards-compat, so we should probably just make it work.

**Comment by outsideris** [comment]
I didn't find a proper approach even if I'm working on it.
